-- Persistent notifications generated by the generate-notifications Edge
-- Function (and a few synchronous spots like schedulePlannedTransaction).
-- Frontend reads from this table via useNotifications hook.

begin;

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null,
  family_id uuid,
  kind text not null,
  severity text not null default 'info' check (severity in ('info','warning','danger','celebrate')),
  title text not null,
  body text,
  link_to text,
  metadata jsonb not null default '{}'::jsonb,
  dedup_key text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create unique index if not exists notifications_dedup
  on public.notifications(user_id, dedup_key)
  where dedup_key is not null;

create index if not exists notifications_user_unread
  on public.notifications(user_id, read_at, created_at desc);

alter table public.notifications enable row level security;

do $$
declare pol record;
begin
  for pol in select policyname from pg_policies where schemaname = 'public' and tablename = 'notifications'
  loop
    execute format('drop policy if exists %I on public.notifications', pol.policyname);
  end loop;
end $$;

create policy "notifications_select_own" on public.notifications
  for select to authenticated using (user_id = auth.uid());
create policy "notifications_update_own" on public.notifications
  for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy "notifications_delete_own" on public.notifications
  for delete to authenticated using (user_id = auth.uid());
create policy "notifications_insert_own" on public.notifications
  for insert to authenticated with check (user_id = auth.uid());

commit;
